#!/usr/bin/env python3
"""Turn google-services.json into the Android string resources Firebase reads at
start-up, so the build does not need the google-services Gradle plugin (which
refuses any package name the JSON does not list, and so blocks the .dev build).

    scripts/firebase-res.py path/to/google-services.json [src-tauri/gen/android]

The output file is git-ignored; it carries the Firebase API key."""
import json, sys, pathlib
from xml.sax.saxutils import escape

src = pathlib.Path(sys.argv[1])
gen = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else "src-tauri/gen/android")
d = json.loads(src.read_text())
info, client = d["project_info"], d["client"][0]
values = {
    "google_app_id": client["client_info"]["mobilesdk_app_id"],
    "gcm_defaultSenderId": info["project_number"],
    "google_api_key": client["api_key"][0]["current_key"],
    "google_crash_reporting_api_key": client["api_key"][0]["current_key"],
    "project_id": info["project_id"],
}
if "storage_bucket" in info:
    values["google_storage_bucket"] = info["storage_bucket"]
out = gen / "app/src/main/res/values/firebase.xml"
out.parent.mkdir(parents=True, exist_ok=True)
body = "\n".join(f'    <string name="{k}" translatable="false">{escape(v)}</string>' for k, v in values.items())
out.write_text(f'<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/firebase-res.py from google-services.json; not committed. -->\n<resources>\n{body}\n</resources>\n')
print(f"wrote {out} for {client['client_info']['android_client_info']['package_name']} (app id {values['google_app_id']})")
