#!/usr/bin/env bash
# Send the working tree to vostro for an Android build.
#
# The catch this exists for: `src-tauri/gen/android` is generated by Tauri, but
# parts of it are ours and tracked — MainActivity.kt, the manifest, the strings,
# the backup rules, the Gradle file. Excluding the whole directory (as the first
# version of this command did) silently builds an APK without those edits, which
# is how builds 25–30 shipped with the backup hardening missing from the manifest.
# So: copy everything tracked, exclude only what the build makes and what must
# never leave this machine.
set -euo pipefail
cd "$(dirname "$0")/.."
rsync -az --delete \
  --exclude node_modules --exclude dist \
  --exclude 'src-tauri/target' --exclude 'src-tauri/crates/*/target' --exclude 'src-tauri/plugins/*/target' \
  --exclude 'src-tauri/gen/apple' \
  --exclude 'src-tauri/gen/android/.gradle' \
  --exclude 'src-tauri/gen/android/build' \
  --exclude 'src-tauri/gen/android/app/build' \
  --exclude 'src-tauri/gen/android/local.properties' \
  --exclude 'src-tauri/gen/android/keystore.properties' \
  --exclude 'src-tauri/gen/android/app/google-services.json' \
  --exclude 'src-tauri/gen/android/app/src/main/res/values/firebase.xml' \
  --exclude keystore.jks --exclude build.json --exclude .git \
  ./ vostro:~/develop/encedo-authenticator/
echo "sent to vostro:~/develop/encedo-authenticator"
