#!/usr/bin/env bash
# Build the .dev test APK on vostro: same code, applicationId with a .dev suffix
# so it installs next to v1 from Google Play. Run on vostro after rsync.
#   scripts/vostro-dev-apk.sh [targets...]   (default: aarch64 x86_64)
set -euo pipefail
source ~/.android-env.sh
SRC=~/develop/encedo-authenticator
DEV=~/develop/encedo-authenticator-dev
TARGETS=("${@:-aarch64 x86_64}")
rsync -a --delete --exclude node_modules --exclude 'src-tauri/target' --exclude 'src-tauri/gen/android/app/build' --exclude 'src-tauri/gen/android/.gradle' --exclude 'permissions/autogenerated' "$SRC/" "$DEV/"
cd "$DEV"
npm install --no-audit --no-fund
# Every build gets a higher versionCode (Android refuses to update otherwise)
# and a numbered file name (so Nextcloud sees a new file, not a cached one).
COUNTER=~/.encedo-dev-build
N=$(( $(cat "$COUNTER" 2>/dev/null || echo 0) + 1 )); echo "$N" > "$COUNTER"
CODE=$(( 2000000 + N ))
# identifier stays the production one here (Tauri looks for the Kotlin dir by it);
# the .dev applicationId is set in build.gradle.kts below.
cat > src-tauri/tauri.android.conf.json <<JSON
{
  "identifier": "com.encedo.mobile.auth.android",
  "productName": "Encedo HEM Auth dev",
  "version": "2.0.0-dev.$N",
  "bundle": { "android": { "versionCode": $CODE } }
}
JSON
sed -i 's/applicationId = "com.encedo.mobile.auth.android"/applicationId = "com.encedo.mobile.auth.android.dev"/' src-tauri/gen/android/app/build.gradle.kts
sed -i 's/<string name="app_name">[^<]*<\/string>/<string name="app_name">Encedo HEM Auth dev<\/string>/; s/<string name="main_activity_title">[^<]*<\/string>/<string name="main_activity_title">Encedo HEM Auth dev<\/string>/' src-tauri/gen/android/app/src/main/res/values/strings.xml
[ -f src-tauri/gen/android/app/src/main/res/values/firebase.xml ] || { echo "missing firebase.xml: run scripts/firebase-res.py first"; exit 1; }
args=(); for t in ${TARGETS[@]}; do args+=(--target "$t"); done
cargo tauri android build --apk "${args[@]}"
BT=$(ls -d ~/Android/Sdk/build-tools/35.0.0)
OUT=src-tauri/gen/android/app/build/outputs/apk/universal/release
"$BT/zipalign" -p -f 4 "$OUT/app-universal-release-unsigned.apk" "$OUT/aligned.apk"
mkdir -p ~/builds
APK=~/builds/encedo-auth-dev-$N.apk
"$BT/apksigner" sign --ks ~/.android/debug.keystore --ks-pass pass:android --key-pass pass:android --out "$APK" "$OUT/aligned.apk"
ln -sf "$APK" ~/encedo-auth-dev.apk
"$BT/aapt" dump badging "$APK" | grep -E "^package|native-code"
ls -la "$APK"
echo "APK=$APK"
