#!/usr/bin/env node
/**
 * Known-answer vectors for the v2 Rust protocol module, produced by the v1
 * JavaScript itself (axlsign.js and crypto-js.js as shipped in the Cordova app
 * on the `main` branch). Everything here is deterministic: fixed seeds stand in
 * for the random bytes v1 draws at runtime.
 *
 *   node tests/vectors/gen.mjs            # writes tests/vectors/v1.json
 *
 * The helpers below are copied from www/js/base.js and index.js on `main`,
 * byte for byte where it matters (JSON field order, base64url, "A" prefix).
 */
import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const dir = mkdtempSync(join(tmpdir(), "v1-"));
for (const f of ["axlsign.js", "crypto-js.js"]) {
  writeFileSync(join(dir, f), execFileSync("git", ["show", `main:www/js/${f}`], { cwd: repo }));
}
const require = createRequire(import.meta.url);
const axlsign = require(join(dir, "axlsign.js"));
const CryptoJS = require(join(dir, "crypto-js.js"));

// ---- v1 helpers (base.js) --------------------------------------------------
const ToBase64 = (u8) => Buffer.from(u8).toString("base64");
const FromBase64 = (s) => new Uint8Array(Buffer.from(s, "base64"));
function base64url(wordArray) {
  return CryptoJS.enc.Base64.stringify(wordArray).replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");
}
function jwt_generate_hs256(header, data, secret) {
  header.alg = "HS256";
  header.typ = "JWT";
  const encodedHeader = base64url(CryptoJS.enc.Utf8.parse(JSON.stringify(header)));
  const encodedData = base64url(CryptoJS.enc.Utf8.parse(JSON.stringify(data)));
  const signature = base64url(CryptoJS.HmacSHA256(encodedHeader + "." + encodedData, secret));
  return encodedHeader + "." + encodedData + "." + signature;
}
const Base64EncodeUrl = (s) => s.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const b64 = (s) => CryptoJS.enc.Base64.parse(s);
const hmacB64 = (msg, keyB64) => CryptoJS.HmacSHA256(msg, b64(keyB64)).toString(CryptoJS.enc.Base64);

// ---- deterministic material ------------------------------------------------
const seed = (tag) => {
  // 32 bytes from a tag, via SHA-256; stable across runs and languages.
  return FromBase64(CryptoJS.SHA256(tag).toString(CryptoJS.enc.Base64));
};
const app = axlsign.generateKeyPair(seed("encedo-v2 vectors: app key"));
const manager = axlsign.generateKeyPair(seed("encedo-v2 vectors: manager key"));
const brokerPair = axlsign.generateKeyPair(seed("encedo-v2 vectors: broker epk pairing"));
const brokerEvent = axlsign.generateKeyPair(seed("encedo-v2 vectors: broker epk event"));
const brokerSession = axlsign.generateKeyPair(seed("encedo-v2 vectors: broker epk session"));

const aid = ToBase64(app.public), aid_prv = ToBase64(app.private), eid = ToBase64(manager.public);
const out = { note: "Generated by tests/vectors/gen.mjs from v1 JavaScript on branch main. Do not edit by hand." };

// ---- X25519 ---------------------------------------------------------------
out.x25519 = [
  { name: "app seed -> keypair", seed: ToBase64(seed("encedo-v2 vectors: app key")), private_clamped: aid_prv, public: aid },
  { name: "app x manager", private: aid_prv, peer_public: eid, shared: ToBase64(axlsign.sharedKey(app.private, manager.public)) },
  { name: "manager x app (symmetry)", private: ToBase64(manager.private), peer_public: aid, shared: ToBase64(axlsign.sharedKey(manager.private, app.public)) },
];

// ---- JWT ------------------------------------------------------------------
out.jwt = [{
  header_in: { ecdh: "x25519" },
  payload: { a: 1, b: "two", c: [3] },
  secret: ToBase64(seed("encedo-v2 vectors: jwt secret")),
  jwt: jwt_generate_hs256({ ecdh: "x25519" }, { a: 1, b: "two", c: [3] }, b64(ToBase64(seed("encedo-v2 vectors: jwt secret")))),
  note: "header serialises as {\"ecdh\":\"x25519\",\"alg\":\"HS256\",\"typ\":\"JWT\"}; payload field order as given",
}];

// ---- pid -> pidx -----------------------------------------------------------
out.pid = ["a+b/c==", "abc", "MTIzNDU2Nzg5MA==", "//++==", "x-y_z"].map((pid) => ({ pid, pidx: Base64EncodeUrl(pid) }));

// ---- pairing (genReply) ----------------------------------------------------
{
  const jti = ToBase64(seed("encedo-v2 vectors: pairing jti").slice(0, 16));
  const eat = 1757260000;
  const epk = ToBase64(brokerPair.public);
  const label = "Pixel 8 (Android)";
  const fid = "fcm-token-example-" + "x".repeat(40);
  const jwt_secret_base64 = ToBase64(axlsign.sharedKey(app.private, manager.public));
  const data = { jti, eat, iss: aid, aud: eid, epk, label };
  const jwt = jwt_generate_hs256({ ecdh: "x25519" }, data, b64(jwt_secret_base64));
  const secret_base64 = ToBase64(axlsign.sharedKey(app.private, brokerPair.public));
  const mac = hmacB64(jwt + fid, secret_base64);
  out.pairing = {
    inputs: { request_payload: { jti, eat, iss: eid, aud: epk }, aid_seed: ToBase64(seed("encedo-v2 vectors: app key")), label, fid },
    derived: { aid, aid_prv, s1: jwt_secret_base64, s_epk: secret_base64 },
    expected: { reply: jwt, mac, post_body: { reply: jwt, fid, mac, aid } },
  };
}

// ---- event: scope decrypt, verify, allow reply ----------------------------
function eventVector(name, scopePlain, { now, periodMin, writable, tamper = false }) {
  const jti = ToBase64(seed("encedo-v2 vectors: event jti " + name).slice(0, 16));
  const epk = ToBase64(brokerEvent.public);
  const exp = now + 120;
  // Shared key material, exactly as executeEvent derives it.
  const secret_base64 = ToBase64(axlsign.sharedKey(app.private, manager.public));
  const hmac_secret_b64 = CryptoJS.HmacSHA256(b64(jti), b64(secret_base64)).toString(CryptoJS.enc.Base64);
  const master = FromBase64(hmac_secret_b64);
  const aes_key_b64 = ToBase64(master.slice(0, 16)), aes_iv_b64 = ToBase64(master.slice(16));
  // What the HEM sends: "A" + base64(AES-CBC(scope) || HMAC(scope, master)).
  const ct_b64 = CryptoJS.AES.encrypt(scopePlain, b64(aes_key_b64), { iv: b64(aes_iv_b64), mode: CryptoJS.mode.CBC }).toString();
  let mac_b64 = hmacB64(scopePlain, hmac_secret_b64);
  if (tamper) { const m = FromBase64(mac_b64); m[0] ^= 0x01; mac_b64 = ToBase64(m); }
  const scope_enc = "A" + ToBase64(Buffer.concat([Buffer.from(ct_b64, "base64"), Buffer.from(mac_b64, "base64")]));
  // Decrypt, as v1 does, to prove the round trip.
  const dec = CryptoJS.AES.decrypt(ct_b64, b64(aes_key_b64), { iv: b64(aes_iv_b64), mode: CryptoJS.mode.CBC }).toString(CryptoJS.enc.Base64);
  const decrypted = Buffer.from(dec, "base64").toString("latin1");
  if (decrypted !== scopePlain) throw new Error("round trip failed");
  const v = {
    name,
    inputs: { aid_prv, aid, eid, event: { jti, scope: scope_enc, epk, exp, ipinfo_eid: { city: "Warsaw", country: "PL", ip: "203.0.113.7" } }, pid: "MTIzNDU2Nzg5MA==", now, period_min: periodMin, writable },
    derived: { s1: secret_base64, master: hmac_secret_b64, aes_key: aes_key_b64, aes_iv: aes_iv_b64, ciphertext: ct_b64, scope_mac: mac_b64 },
    expected: { scope: scopePlain, mac_valid: !tamper },
  };
  if (!tamper) {
    let scopeTmp = scopePlain.replace(":rw", "");
    if (writable) scopeTmp = scopeTmp.concat(":rw");
    const rep_mac_b64 = hmacB64(scopeTmp, hmac_secret_b64);
    const rep_enc_b64 = CryptoJS.AES.encrypt(scopeTmp, b64(aes_key_b64), { iv: b64(aes_iv_b64), mode: CryptoJS.mode.CBC }).toString();
    const encoded_scope = "A" + ToBase64(Buffer.concat([Buffer.from(rep_enc_b64, "base64"), Buffer.from(rep_mac_b64, "base64")]));
    const expo = periodMin === 15 ? now + 15 * 60 : now + (periodMin / 60) * 60 * 60;
    const dataX = { aud: eid, jti, exp: expo, iat: now, pid: "MTIzNDU2Nzg5MA==", iss: aid, scope: encoded_scope };
    const jwt = jwt_generate_hs256({ ecdh: "x25519" }, dataX, b64(secret_base64));
    const reply_secret = ToBase64(axlsign.sharedKey(app.private, brokerEvent.public));
    const reply_mac_b64 = hmacB64(jwt, reply_secret);
    v.expected.reply = { scope_sent: scopeTmp, scope_enc: encoded_scope, exp: expo, authreply: jwt, mac: reply_mac_b64, s_epk: reply_secret };
  }
  return v;
}
const now = 1757270000;
const keyLabel = Buffer.from(JSON.stringify({ t: "0221", l: "PGP main" })).toString("base64");
out.events = [
  eventVector("keymgmt use, 1 h", `keymgmt:use:2ba3f1e0c9a4b7d8e6f5a3c2b1d0e9f84c91e#${keyLabel}`, { now, periodMin: 60, writable: false }),
  eventVector("storage disk0 rw, 15 min", "storage:disk0", { now, periodMin: 15, writable: true }),
  eventVector("storage disk0 rw stripped, 24 h", "storage:disk0:rw", { now, periodMin: 1440, writable: false }),
  eventVector("system upgrade, 8 h", "system:upgrade", { now, periodMin: 480, writable: false }),
  eventVector("tampered mac", "logger:del", { now, periodMin: 15, writable: false, tamper: true }),
];

// ---- unpair ---------------------------------------------------------------
{
  const epk = ToBase64(brokerSession.public);
  const nonce = ToBase64(seed("encedo-v2 vectors: unpair nonce"));
  const secret_base64 = ToBase64(axlsign.sharedKey(app.private, brokerSession.public));
  out.unpair = {
    inputs: { aid_prv, aid, pid: "MTIzNDU2Nzg5MA==", epk, nonce },
    derived: { s_epk: secret_base64 },
    expected: { mac: hmacB64(b64(nonce), secret_base64), post_body: { pid: "MTIzNDU2Nzg5MA==", epk, nonce, mac: hmacB64(b64(nonce), secret_base64), aid } },
  };
  // [v2] token refresh: HMAC(nonce || utf8(fid), S_epk)
  const fid = "fcm-token-example-" + "y".repeat(40);
  const msg = CryptoJS.lib.WordArray.create(Buffer.concat([Buffer.from(nonce, "base64"), Buffer.from(fid, "utf8")]));
  out.token_refresh = { inputs: { aid_prv, aid, pid: "MTIzNDU2Nzg5MA==", epk, nonce, fid }, expected: { mac: CryptoJS.HmacSHA256(msg, b64(secret_base64)).toString(CryptoJS.enc.Base64) } };
}

const file = join(here, "v1.json");
writeFileSync(file, JSON.stringify(out, null, 2) + "\n");
console.log(`wrote ${file}: ${out.events.length} events, pairing, unpair, ${out.x25519.length} x25519, ${out.pid.length} pid`);
